### ISSUE TITLE
[Feature] Progressive Web Application (PWA)

### ISSUE THREAD

**Issue by danieldanielecki** [eduardconstantin/azure-cloud-exams#101]
https://github.com/shadowwalker/next-pwa and https://medium.com/geekculture/how-to-make-a-next-js-app-a-pwa-a5e2b13da548 should make it happen!

**Comment by Pahul-Sidhu** [comment]
I would like to work on this as well

**Comment by danieldanielecki** [comment]
right, will be implemented in https://github.com/Ditectrev/Practice-Exams-Platform/issues/2, the project is being developed over there 👍

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Practice-Exams-Platform/commit/6cf8925777d3ec926438c3f2f1cc743680ffc3c6
