### ISSUE TITLE
[Feature] Add types to useResults file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#124]
**Is your feature request related to a problem? Please describe.**
The useResults test file does not have types

**Describe the solution you'd like**
Change the file type from .js to .tsx
Add types inside the file

**Additional context**
https://github.com/eduardconstantin/azure-cloud-exams/blob/main/profilerFunctions/useResults.js

**Comment by sushant0709** [comment]
Hey! Can you assign me this issue? The js file needs to have type safety and hence converted to ts, right? Is my understanding correct?

**Comment by eduardconstantin** [comment]
yes, that's right

**Comment by eduardconstantin** [comment]
@sushant0709 are you still working on this issue?

**Comment by sushant0709** [comment]
@eduardconstantin yes, would complete it by this weekend.
