### ISSUE TITLE
[BUG] Exam mode score issue

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#125]
**Describe the bug**
Some users reported the in the exam mode the final score is never 100 even if they answer correctly all the questions.
https://github.com/Ditectrev/Practice-Exams-Platform/pull/45#issuecomment-2342986040

**To Reproduce**
1. Go to Exam Mode
2. Answer all questions correctly
4. See score

**Expected behavior**
If all questions are correctly answered the score should be 100.

**Screenshots**
![image](https://github.com/user-attachments/assets/37bdf619-0579-4a9e-9462-c3a11cb1d899)

**Comment by chaitanya-bhargava** [comment]
Hey @eduardconstantin, is this the same issue as Ditectrev/#45? i.e. the score is getting divided by the total no. of answers in case of multiple choice questions. if yes then, I can do the same fix and you can assign it to me.

**Comment by mutant138** [comment]
Kindly assign this to me!

**Comment by eduardconstantin** [comment]
> Hey @eduardconstantin, is this the same issue as Ditectrev/#45? i.e. the score is getting divided by the total no. of answers in case of multiple choice questions. if yes then, I can do the same fix and you can assign it to me.

Yes, but from my understanding it is the last question that is not added to the final score, you have to check in the app. You can also check the pr from ditectrev.

**Comment by eduardconstantin** [comment]
> Kindly assign this to me!

Let's give @chaitanya-bhargava a chance first.
