### ISSUE TITLE
[Feature] Change input selection icon

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#127]
**Is your feature request related to a problem? Please describe.**
Someone said that the x icon from the selection input is misleading and it should be changed to something more intuitive.

**Describe the solution you'd like**
The "x" inside the circle needs to go and have only a full circle.

This is the svg path code that needs to be added for the radio input
`M 16 8 A 8 8 0 1 1 0 8 a 8 8 0 0 1 16 0 z z`
And this is for the checkbox input:
`M 2 0 a 2 2 0 0 0 -2 2 v 12 a 2 2 0 0 0 2 2 h 12 a 2 2 0 0 0 2 -2 V 2 a 2 2 0 0 0 -2 -2 H 2 z z`
The the code can be found in components/SelectionInput.tsx

**Additional context**
This is the current input
![image](https://github.com/user-attachments/assets/bed2ea4a-a766-4263-9a2d-ef7e51d07b3e)

This is how it should look like
![image](https://github.com/user-attachments/assets/c166f7fa-33da-455a-b026-14b31f2f2dae)

**Comment by maxwithbug** [comment]
@eduardconstantin fixed it
