### ISSUE TITLE
[BUG] Checkbox selection not visible

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#130]
**Describe the bug**
For questions that have more than one answer the options should have a checkbox not a radio button.

**To Reproduce**
1. Go to Practice Mode
2. In the upper part of the screen set 12
3. Select multiple options
4. See rounded checkbox inputs

**Expected behavior**
If the type of the input is radio the option should show a circle, if the type is checkbox it should show a square
The files where the code needs to change are:
components/QuizExamForm.tsx
components/SelectionInput.tsx

**Screenshots**
Radio buttons
![image](https://github.com/user-attachments/assets/5684d346-0625-4feb-82e1-5d7c988d9b17)

Desired checkbox
![image](https://github.com/user-attachments/assets/4b863f32-e400-443b-b9e4-363c63438c59)

**Additional info**
The path for the svg has a condition based on the type of the input, it should have only this code
`d="M 2 0 a 2 2 0 0 0 -2 2 v 12 a 2 2 0 0 0 2 2 h 12 a 2 2 0 0 0 2 -2 V 2 a 2 2 0 0 0 -2 -2 H 2 z z"`

**Comment by eduardconstantin** [comment]
@maxwithbug you can take this one

**Comment by maxwithbug** [comment]
@eduardconstantin thank you

**Comment by maxwithbug** [comment]
@eduardconstantin Finished it please give it a review

**Comment by maxwithbug** [comment]
@eduardconstantin i think now it should be fine
