### ISSUE TITLE
[Feature] Not Found text after using search

### ISSUE THREAD

**Issue by danieldanielecki** [eduardconstantin/azure-cloud-exams#133]
Currently, whenever using search, and typing not existing resources, the user sees an empty page.
It'd be great to at least have a text there's nothing found.
![Screenshot 2024-10-09 at 17 27 02](https://github.com/user-attachments/assets/18644321-0adc-49a6-9df6-6273da251cb6)

**Comment by eduardconstantin** [comment]
Did I add a search input to mine?

**Comment by danieldanielecki** [comment]
No, sorry. I confused the forks.

**Comment by danieldanielecki** [comment]
@eduardconstantin, what about having something on the last page of the exam? I think it's also for your codebase.

![image](https://github.com/user-attachments/assets/ed5a63db-4c69-4c87-9be1-a87293c8cd61)

**Comment by eduardconstantin** [comment]
I think that is the practice mode, it should go to the first question if you press next

**Comment by danieldanielecki** [comment]
> I think that is the practice mode, it should go to the first question if you press next

Yes, some kind of overview would be nice, I think.
