### ISSUE TITLE
[Feature] Replace formik with useForm

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#134]
**Is your feature request related to a problem? Please describe.**
The exam mode form uses formik to handle the form responses, the practice mode form uses useForm.

**Describe the solution you'd like**
Replace formik functionality with useFrom.
Delete formik package.
This is the file: components/QuizExamForm.tsx

**Comment by Virtual4087** [comment]
I would like to work on this

**Comment by eduardconstantin** [comment]
please create a new branch from dev

**Comment by eduardconstantin** [comment]
@Virtual4087 are you working on this issue?

**Comment by Virtual4087** [comment]
@eduardconstantin I am really sorry, I was out of town for a few days and forgot to inform you. I'll unassign myself. Sorry once again.
