### ISSUE TITLE
[BUG] Selection issue with multiple choice questions

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-cloud-exams#137]
**Describe the bug**
There is an issue with multiple choice questions, when I select two or more options and click on reveal answer the selection disappears, same thing happens when I move to next question and return to the question with multiple choices.
 
**To Reproduce**
1. Go to Practice Mode
2. Go to question 12
3. Select multiple options
4. Click reveal answer
5. See error

**Expected behavior**
When I select two or more options and click on reveal answer the selected options should remain selected.

**Screenshots**

https://github.com/user-attachments/assets/3680e7e1-9188-4a98-8797-442c8c0732bc

**Comment by Zish303** [comment]
@eduardconstantin I want to work on this issue.

**Comment by eduardconstantin** [comment]
I'll work on this, I forgot to assign myself.
